#!/bin/bash
#
# initrd_create:  make initrd rootdisk
#
# Author:	  Tomas Matejicek <http://www.linux-live.org>

. ../config || exit 1
. ./liblinuxlive || exit 1 

KERNEL=`/bin/uname -r`

echo "creating empty image file initrd.img..."
dd if=/dev/zero of=$INITRDIMG bs=1024 count=$RAM0SIZE >/dev/null 2>/dev/null

echo "making filesystem..."
mkfs -t ext2 -F -m 0 -i 1024 $INITRDIMG >/dev/null 2>/dev/null

echo "creating empty directory $MOUNTDIR..."
rm -Rf $MOUNTDIR
mkdir $MOUNTDIR

echo "mounting initrd.img to it..."
mount -o loop $INITRDIMG $MOUNTDIR

echo "creating directories..."
rmdir $MOUNTDIR/lost+found
mkdir -p $MOUNTDIR/{etc,dev,bin,mnt,proc,sbin,lib,tmp,usr/bin,usr/sbin,var/log}

echo "copying files to the rootdisk (this may take some time)..."
touch $MOUNTDIR/etc/{m,fs}tab
cp {linuxrc,liblinuxlive} $MOUNTDIR # symlink will be copied as original file
chmod a+x $MOUNTDIR/linuxrc

# find all lib dependences
for BINARY in cp chmod touch tar gzip gunzip rm bash sh mount umount mv cut \
              mkdir rmdir ls ln echo cat grep egrep fdisk blockdev \
	      pivot_root insmod lsmod modprobe depmod swapon eject tail tr \
	      chroot readlink basename dirname test sleep [ ;
do
   for LOCATION in /bin /sbin /usr/bin /usr/sbin ;
   do
      if [ -r "$LOCATION/$BINARY" ]; then
         rcopy "$LOCATION/$BINARY" "$MOUNTDIR"

         list_libs "$LOCATION/$BINARY" | sort | uniq | while read LIB; do
            if [ ! -a "$MOUNTDIR/$LIB" ]; then
               rcopy "$LIB" "$MOUNTDIR"
	    fi
	 done
      fi
   done
done

# this line can be safely removed when using 2.6 kernel
cp -R /sbin/*.old $MOUNTDIR/sbin 2>/dev/null

#filesize script by using ls + cut
echo -ne "#!/bin/bash\necho \`ls -ol \"\$1\"\` | cut -d \" \" -f 4" >$MOUNTDIR/bin/filesize
chmod 0755 $MOUNTDIR/bin/filesize

LMK="lib/modules/$KERNEL"

#necessary modules and dependency files
rcopy /$LMK/kernel/fs/ovlfs $MOUNTDIR

#copy filesystem modules, if not directly copied into kernel
rcopy /$LMK/kernel/fs/ntfs $MOUNTDIR 2>/dev/null
rcopy /$LMK/kernel/fs/ext3 $MOUNTDIR 2>/dev/null
rcopy /$LMK/kernel/fs/reiserfs $MOUNTDIR 2>/dev/null

#usb modules
rcopy /$LMK/kernel/drivers/usb/usbcore.* $MOUNTDIR 2>/dev/null
rcopy /$LMK/kernel/drivers/usb/host $MOUNTDIR 2>/dev/null
rcopy /$LMK/kernel/drivers/usb/storage $MOUNTDIR 2>/dev/null

#disk (ide, raid, pcmcia, pnp, ide-scsi) modules
rcopy /$LMK/kernel/drivers/ide $MOUNTDIR
rcopy /$LMK/kernel/drivers/pcmcia $MOUNTDIR
rcopy /$LMK/kernel/drivers/pnp $MOUNTDIR
rcopy /$LMK/kernel/drivers/scsi/ide-scsi.* $MOUNTDIR

chroot $MOUNTDIR depmod -a 2>/dev/null # some dependences may be missing

echo "unmounting $MOUNTDIR and gzipping initrd.img..."
umount $MOUNTDIR
gzip --best $INITRDIMG

echo "deleting directory $MOUNTDIR..."
rm -Rf $MOUNTDIR
