#!/bin/bash
# initrd_create:  make initrd rootdisk by using busybox
#
# Author:	  Tomas M. <http://www.linux-live.org>

. ../.config || exit 1

# rcopy is a recursive cp, which copies also symlink's real source
# $1 = source (may be a regular file or symlink)
# $2 = target PARENT
#
rcopy()
{
   CWD=`pwd`
   cd $ROOT
   SOURCE="${1:${#ROOT}}"
   DEST="$2"
   if [ -L "$SOURCE" ]; then
      REALPATH="`readlink -f \"$SOURCE\"`"
      cp --parent -R "$REALPATH" "$DEST"
      ln -sf "$REALPATH" "$DEST/$SOURCE"
   else
      cp --parent -R "$SOURCE" "$DEST"
   fi
   if [ "$?" -ne 0 ]; then
      echo ""
      echo "---------------------------"
      echo "Error occured while trying to copy \"$SOURCE\""
      echo "Possible reason: not enough free space in initrd OR source doesn't exist."
      echo "If space is your issue, see '.config' file to increase size of initrd."
      echo "If source file doesn't exist, it's a big problem. See DOC/requirements.txt"
      echo "---------------------------"
      exit 1
   fi
   cd $CWD
}

# copy file/dir only if it exists, else skip with no error
# $1 = source (may not exist)
# $2 = target PARENT
#
rcopy_ex()
{
   if [ -a "$1" ]; then
      rcopy "$1" "$2"
   fi
}

debug()
{
   echo "$@" >>$DEBUG
   return 0
}

##################################################
# Create INITRD image now:

MOUNTDIR=/tmp/initrd_mountdir_$$
INITRD_TREE=/tmp/initrd_tree_$$
INITRDIMG=initrd

if [ ! -d $ROOT/$LMK ]; then
   echo "cannot find your kernel modules (*.ko) in $ROOT/$LMK"
   exit 1
fi

if [ "`ls -1 rootfs/lib`" = "" ]; then
   echo "cannot find essential libc libraries."
   echo "please add ld-linux and libc.so to `pwd`./rootfs/lib"
   exit 1
fi

debug "creating empty directory $INITRD_TREE"
rm -Rf $INITRD_TREE
mkdir $INITRD_TREE

debug "creating directories"
mkdir -p $INITRD_TREE/{etc,dev,bin,mnt,proc,lib,sys,tmp,var/log}

debug "creating some essential devices in rootdisk"
mknod $INITRD_TREE/dev/console c 5 1
mknod $INITRD_TREE/dev/null c 1 3
mknod $INITRD_TREE/dev/ram b 1 1
mknod $INITRD_TREE/dev/systty c 4 0
mknod $INITRD_TREE/dev/tty c 5 0
for i in 1 2 3 4 5 6; do
  mknod $INITRD_TREE/dev/tty$i c 4 $i;
done

debug "copying files to the rootdisk"
touch $INITRD_TREE/etc/{m,fs}tab
cat liblinuxlive | sed -r 's/^LIVECDNAME=.*/LIVECDNAME="'$LIVECDNAME'"/' > $INITRD_TREE/liblinuxlive
cp {linuxrc,cleanup} $INITRD_TREE
chmod ago+x $INITRD_TREE/{linuxrc,cleanup}

cp -R rootfs/* $INITRD_TREE
ln -s busybox $INITRD_TREE/bin/ash
ln -s busybox $INITRD_TREE/bin/sh
ln -s busybox $INITRD_TREE/bin/bash
ln -s busybox $INITRD_TREE/bin/echo
ln -s busybox $INITRD_TREE/bin/[
ln -s busybox $INITRD_TREE/bin/mount
ln -s busybox $INITRD_TREE/bin/umount
ln -s busybox $INITRD_TREE/bin/poweroff
ln -s busybox $INITRD_TREE/bin/halt
ln -s busybox $INITRD_TREE/bin/reboot
ln -s busybox $INITRD_TREE/bin/ld
ln -s busybox $INITRD_TREE/bin/ls
ln -s busybox $INITRD_TREE/bin/head
ln -s busybox $INITRD_TREE/bin/cat
ln -s busybox $INITRD_TREE/bin/grep
ln -s busybox $INITRD_TREE/bin/sleep
ln -s busybox $INITRD_TREE/bin/sed
ln -s busybox $INITRD_TREE/bin/mdev
ln -s bin $INITRD_TREE/sbin

# necessary modules and dependency files
mkdir -p $INITRD_TREE/$LMK/kernel/fs
rcopy $ROOT/$LMK/kernel/fs/aufs $INITRD_TREE
rcopy $ROOT/$LMK/kernel/fs/squashfs $INITRD_TREE

# copy filesystem modules, if not directly copied into kernel
rcopy_ex $ROOT/$LMK/kernel/lib/zlib_inflate $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/lib/zlib_deflate $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/drivers/block/loop.* $INITRD_TREE 2>>$DEBUG

rcopy_ex $ROOT/$LMK/kernel/fs/isofs $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/fs/fat $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/fs/vfat $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/fs/ntfs $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/fs/ext3 $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/fs/reiserfs $INITRD_TREE 2>>$DEBUG

# add language support for filesystems
rcopy_ex $ROOT/$LMK/kernel/fs/nls/nls_cp437.* $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/fs/nls/nls_iso8859-1.* $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/fs/nls/nls_iso8859-2.* $INITRD_TREE 2>>$DEBUG

# usb modules
rcopy_ex $ROOT/$LMK/kernel/drivers/usb/storage $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/drivers/usb/host/ehci-hcd.* $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/drivers/usb/host/ohci-hcd.* $INITRD_TREE 2>>$DEBUG
rcopy_ex $ROOT/$LMK/kernel/drivers/usb/host/uhci-hcd.* $INITRD_TREE 2>>$DEBUG

debug "unpacking all kernel modules for initrd"
find $INITRD_TREE -name "*.ko.gz" | xargs -r gunzip

debug "generating module dependency files"
depmod -b $INITRD_TREE $KERNEL

debug "creating empty image file for initrd"
dd if=/dev/zero of=$INITRDIMG bs=1024 count=$RAM0SIZE >>$DEBUG 2>&1

debug "making filesystem"
mkfs -t ext2 -F -m 0 -b 1024 -i 1024 $INITRDIMG >>$DEBUG 2>&1

debug "creating empty directory $MOUNTDIR"
rm -Rf $MOUNTDIR
mkdir $MOUNTDIR

debug "mounting $INITRDIMG to it"
modprobe loop 2>>$DEBUG
mount -o loop $INITRDIMG $MOUNTDIR
if [ "$?" -ne 0 ]; then
   echo "Error mounting initrd! Not enough free loop devices?"
   exit 1
fi

debug "copying content of $INITRD_TREE to $MOUNTDIR"
rmdir $MOUNTDIR/lost+found
cp -R --preserve $INITRD_TREE/* $MOUNTDIR

debug "unmounting $MOUNTDIR"
umount $MOUNTDIR

debug "gzipping $INITRDIMG"
gzip --best $INITRDIMG

debug "deleting directory $MOUNTDIR"
rmdir $MOUNTDIR

debug "deleting directory $INITRD_TREE"
rm -Rf $INITRD_TREE

debug "$INITRDIMG.gz created"
