#!/bin/bash
# This is a config file for runme.sh script.

# compressed directories (img) will be stored here
# (the whole folder will be erased now!)
CDDATA=/tmp/live_data_$$

# name of initrd image
INITRDIMG=initrd

# temporary folder for mounting IMGs
# (this folder will be completly erased!)
MOUNTDIR=/tmp/live_tmp_mountdir_$$

# the size of RAMdisk (in KBytes)
# if you change this, then you will need to change the size 
# also in files: bootfiles/isolinux.cfg and tools/DOS/linux.bat
RAM0SIZE=7777
