#!/bin/bash
# convert directory tree into IMG compressed file
# which can be used as a LiveCD module
#
# Author: Tomas Matejicek <http://www.linux-live.org>
#

if [ -a ./liblinuxlive ]; then
   . ./liblinuxlive
else
   . /usr/lib/liblinuxlive || exit 1
fi

if [ ! -d "$1" -o "$3" = "" ]; then
   echo
   echo "Convert directory tree into IMG compressed module"
   echo "usage: $0 source_directory output_file.img virtual_directory_tree"
   exit 1
fi


mkciso "$1" "$2" "$3"
if [ $? != 0 ]; then echo "error building compressed image"; exit 1; fi
