#!/bin/bash
# install img file to SLAX (for harddisk installed SLAX only)
# This will mount the module in TMP and then copy the content
# (uncompressed) to root directory /.
#
# Author: Tomas Matejicek <http://www.linux-live.org>
#

if [ "$1" = "" ]; then
   echo 
   echo "Install IMG compressed module (unpack it and copy to /)"
   echo "usage: $0 source_file.img"
   exit 1
fi

if [ -a ./liblinuxlive ]; then
   . ./liblinuxlive
else
   . /usr/lib/liblinuxlive || exit 1
fi


TMPDIR=/tmp
TMPFILE="/tmp/ll$$"

mount_img "$1" "$TMPDIR" "$TMPFILE"
IMGDIR="`cat $TMPFILE`"
cp -R --preserve "$IMGDIR"/data/* "/"
if [ -x "$IMGDIR/manual" ]; then "$IMGDIR/manual"; fi

umount "$IMGDIR"
umount "$IMGDIR"
rm "$TMPFILE"
rmdir "$IMGDIR"
