#!/bin/ash

# Functions library :: for Linux Live scripts 6.x.y
# Author: Tomas M. <http://www.linux-live.org>
#

# ===========================================================
# variables
# ===========================================================

# linux live flag to fstab, if fstab line doesn't contain it,
# never remove it from fstab automatically (user added it)
FSTABLLFLAG="# AutoUpdate"

# We have to set these variables very carefully
UNION=union
MEMORY=memory
MOUNTDIR=mnt
CHANGES=$MEMORY/changes
COPY2RAM=$MEMORY/copy2ram
IMAGES=$MEMORY/images
INITRAMDISK=$MOUNTDIR/live
LOOPMOUNT=$MOUNTDIR/tmp

# this will be replaced by build script, so don't change the following line!
LIVECDNAME="linux"

# ===========================================================
# user interface functions
# ===========================================================

# echogreen will echo $@ in green color
# $1 = text
#
echogreen()
{
   echo -ne "[0;32m""$@""[0;39m"
}

# echolog
# $1 = text to show and to write to /var/log/messages
#
echolog()
{
   if [ "$1" != "" ]; then
      echogreen "* "
      log "LIVECD:" "$@" 
      echo "$@"
   fi
}

# log
# store given text in /var/log/livedbg
log()
{
   echo "$@" >>/var/log/livedbg
}

# debug
# commands executed when debug boot parameter is present
#
debug()
{
   echo
   echo "====="
   echo ": Debugging started. Here is the root shell for you."
   echo ": Type your desired command or hit Ctrl+D to continue booting."
   echo
   ash < /dev/console
   echo
}

# header
# $1 = text to show
#
header()
{
   echo "[0;1m""$@""[0;0m"
}

fatal()
{
   echolog
   header "Fatal error occured - $1"
   echolog "Something went wrong and we can't continue. This should never happen."
   echolog "Please reboot your computer with Ctrl+Alt+Delete ..."
   echolog
   umount -a -r 2>/dev/null
   mount -t proc proc /proc
   mount -t sysfs sysfs /sys
   ash < /dev/console
}

allow_only_root()
{
  # test if the script is started by root user. If not, exit
  if [ "0$UID" -ne 0 ]; then
     echo "Only root can run `basename $0`"; exit 1
  fi
}

# ===========================================================
# text processing functions
# ===========================================================

# egrep_o is a replacement for "egrep -o". It prints only the last
# matching text
# $1 = regular expression
#
egrep_o()
{
   SED="`echo \"$1\" | sed -r 's/\\//\\\\\\//g'`"
   cat | egrep "$1" | sed -r "s/.*$SED.*/\\1/" 2>/dev/null
}

# look into cmdline and echo $1 back if $1 is set
# $1 = value name, case sensitive, for example changes
# $2 = file to use instead /proc/cmdline, optional
#
cmdline_parameter()
{
   CMDLINE=/proc/cmdline
   if [ "$2" != "" ]; then CMDLINE="$2"; fi
   log "searching for boot param: $1"
   cat "$CMDLINE" | egrep_o "((^|[[:space:]]+)$1(\$|=|[[:space:]]+))" | egrep_o "($1)"
}

# look into cmdline and echo value of $1 option
# $1 = value name, case sensitive, for example livecd_subdir
# $2 = file to use instead /proc/cmdline, optional
#
cmdline_value()
{
   CMDLINE=/proc/cmdline
   if [ "$2" != "" ]; then CMDLINE="$2"; fi
   log "searching for bootparam value: $1"
   cat "$CMDLINE" | egrep_o "((^|[[:space:]]+)$1=([^[:space:]]+))" | egrep_o "(=.*)" | cut -b 2- | tail -n 1
}

# ===========================================================
# system functions
# ===========================================================

# modprobe module $1, including all dependencies, suppress all messages
# (own function because modprobe in busybox doesn't work with gzipped modules)
# $1 = module name, eg. ehci-hcd
# $2 = optional argument
#
modprobe_module()
{
  if [ "$1" = "" ]; then return 1; fi
  modprobe $1 $2 2>/dev/null
}

# Mount device $1 to $2
# $1 = /dev device to mount, eg. /dev/hda1, or loop file, or directory
# $2 = mountpoint, eg. /mnt/hda1
# $3 = optional mount options, for example "ro", or "remount,rw"
# $4 = optional filesystem type
#
mount_device()
{
  # make sure we have enough arguments
  if [ "$2" = "" ]; then return 1; fi

  mkdir -p "$2"
  OPTIONS="noatime"
  if [ -f "$1" ]; then OPTIONS="$OPTIONS,loop"; fi
  if [ -d "$1" ]; then OPTIONS="$OPTIONS,rbind"; fi
  if [ "$3" ]; then OPTIONS="$OPTIONS,$3"; fi
  if [ "$4" ]; then FILESYSTEM="-t $4"; else FILESYSTEM=""; fi

  PRINTK=`cat /proc/sys/kernel/printk`
  echo "0" >/proc/sys/kernel/printk

  mount $FILESYSTEM -o $OPTIONS "$1" "$2" >/dev/null 2>/dev/null
  err=$?

  if [ 0$err -ne 0 ]; then rmdir $2 2>/dev/null; fi
  echo "$PRINTK" >/proc/sys/kernel/printk
  return $err
}

# Force unmount of all parameters
# $1..$n = directories to be unmounted
#
fumount()
{
   while [ "$1" ]; do
      umount "$1" >/dev/null 2>&1
      if [ $? -ne 0 ]; then
         umount -l "$1" >/dev/null 2>&1
      fi
      shift
   done
}

# ===========================================================
# live module functions
# ===========================================================

# Create module
# call mksquashfs with apropriate arguments
# $1 = directory which will be compressed to squashfs module
# $2 = output filesystem module file
# $3 = optional -keep-as-directory argument
#
create_module()
{
   mksquashfs "$1" "$2" $3 >/dev/null
   if [ $? -ne 0 ]; then return 1; fi
   chmod oga-wx "$2" # remove execute attrib
}

# Mountpoint exits with 0 if $1 is mountpoint, else exits with 1
# $1 = directory
#
mountpoint()
{
   cat /proc/mounts | cut -d " " -f 2 | egrep "^$1\$" >/dev/null 2>&1
}

# Mount filesystem module to destination directory
# $1 = path to the compressed module
# $2 = destination folder
#
mount_module()
{
   mount -t squashfs -o loop,ro "$1" "$2"
   err=$?
   if [ 0$err -eq 0 ]; then
      echo "$1 $2" >>/tmp/_mounts
   fi
   return $err
}

# Insert a directory tree $2 to an union specified by $1
# Top-level read-write branch is specified by it's index 0
# $1 = union absolute path (starting with /)
# $2 = path to data directory
#
union_insert_dir()
{
    mount -n -o remount,add:1:$2=ro aufs $1
}

# List all modules in all directories (base, modules, optional)
# and filter out unneeded optional modules (not specified by load= kernel parameter)
# separator for load and noload arguments is "," or ";"
# $1 = root directory of mounted DATAdir
#
list_modules()
{
   LOAD="`cmdline_value load | sed -r 's/\*/.\*/g' | sed -r 's/,|;/|/g'`"
   NOLOAD="`cmdline_value noload | sed -r 's/\*/.\*/g' | sed -r 's/,|;/|/g'`"
   find $1/base $1/modules $1/optional -name "*.lzm" 2>/dev/null | sort | while read LINE; do
      MODNAME="`echo $LINE | cut -b ${#1}- | cut -b 2-`"
      if [ "`echo $LINE | grep /optional/`" ]; then
         if [ ! "$LOAD" -o ! "`echo $MODNAME | egrep -i \"$LOAD\"`" ]; then continue; fi
      fi
      if [ "$NOLOAD" -a "`echo $MODNAME | egrep -i \"$NOLOAD\"`" ]; then continue; fi
      echo $LINE
   done
}

# Insert one single filesystem module to the union
# $1 = union absolute path
# $2 = module full path
# $3 = destination folder, where images will be mounted to
# $4 = preffix length strip (number of characters)
#
union_insert_module()
{
   TARGET="$3/`basename $2`"
   if mountpoint $TARGET >/dev/null 2>&1; then return; fi # skip mounted modules
   mkdir -p $TARGET
   mount_module $2 $TARGET
   if [ $? -ne 0 ]; then echo "Cannot read module data. corrupted download?" >&2; return 1; fi
   union_insert_dir $1 $TARGET
   if [ $? -ne 0 ]; then echo "can't insert module to union" >&2; return 2; fi
   echo "$2" | cut -b $4- | cut -b 2-
   echolog "$2" >/dev/null
   return 0
}

# Insert all filesystem modules, in $2 directory and subdirectories, to the union
# $1 = union absolute path (starting with /)
# $2 = LiveCD data dir (with directories /base, /modules, etc.)
# $3 = destination folder, where images will be mounted to
#
union_insert_modules()
{
   list_modules $2 | while read MODULE; do
      echolog -n " -> "
      union_insert_module $1 $MODULE $3 ${#2}
   done
}

# Copy LiveCD modules to RAM directory
# will copy only /boot, and module files from $1
# $1 = data directory
# $2 = target directory in RAM
#
copy_to_ram()
{
   cp -a "$1/rootcopy" "$2" 2>/dev/null # could be empty
   list_modules "$1" | while read MODULE; do
      TARGET="$2/`basename \`dirname $MODULE\``"
      mkdir -p "$TARGET"
      cp "$MODULE" "$TARGET"
      if [ $? -ne 0 ]; then fatal "Not enough memory. Using ramsize=$RAMSIZE"; fi
   done
}

# ===========================================================
# discovery functions
# ===========================================================

# List all CD-ROMs
# by using /proc entries
#
list_cdrom_devices()
{
   if [ "`cmdline_parameter nocd`" != "" ]; then return 1; fi
   for CDDEVICE in `cat /proc/sys/dev/cdrom/info 2>/dev/null | head -n 3 | tail -n 1 | cut -d ":" -f 2`; do
      echo "/dev/$CDDEVICE"
   done
}

# List all devices with filesystems
# Return empty result when nohd parameter was given.
#
list_partition_devices()
{
   if [ "`cmdline_parameter nohd`" != "" ]; then return 1; fi
   cat /proc/partitions | grep -v loop |grep -v major | grep -v "^\$" | sed -r "s/^[0-9 ]+/\\/dev\\//"
}

# List all disk devices
#
list_disk_devices()
{
   list_partition_devices | egrep -v "[0-9]"
}

# List all partitions marked as Linux Swap
#
list_swap_devices()
{
   if [ "`cmdline_parameter nohd`" != "" -o "`cmdline_parameter noswap`" != "" ]; then return 1; fi
   blkid -t TYPE="swap" | cut -d : -f 1
}

# List all block devices
#
list_block_devices()
{
   list_cdrom_devices
   list_partition_devices
}

# Find file-path on given device
# First it mounts the device in $1 read-only. If the path is found, 
# then remount read-write and return the path, else unmounts and exits
# $1 = mountpoint, eg. /mnt
# $2 = device
# $3 = path/filename
#
find_filepath()
{
   DIR="$1/`basename $2`"
   mountpoint $DIR >/dev/null 2>&1
   if [ $? -ne 0 ]; then
      mount_device $2 $DIR ro
      if [ $? -ne 0 ]; then rmdir $DIR 2>/dev/null; return 1; fi
   fi
   FOUND="`ls -A1d $DIR/$3 2>/dev/null | head -n 1 | tr -s '/'`"
   umount $DIR 2>/dev/null

   if [ "$FOUND" = "" ]; then
      rmdir $DIR 2>/dev/null
      return 1
   else
      # mount again, without the 'ro' option now, so use rw or defaults
      mount_device $2 $DIR 
      echo "$FOUND"
      return 0
   fi
}

# Find file in computer by mounting disks or other storage devices in $1
# and searching for $2 in the mounted directory
# $1 = mountpoint, eg. /mnt
# $2 = filename or device-path or devicepath/filename
#
find_file()
{
   # if parameter is just a device, echo it and exit
   if [ -b "$2" -o -c "$2" -o "$2" = "" ]; then echo "$2"; return; fi

   # If path doesn't start with /dev/, try to find the exact path on all devices
   # First, split DEV/PATH parts
   DEVPART="`echo \"$2\" | egrep_o \"(^/dev/[^/]+)\"`"

   if [ "$DEVPART" = "" ]; then
      # no device is specified, search all devices for filename $1
      PATHPART="$2";
      list_block_devices | while read DEVICE; do
         find_filepath $1 $DEVICE $PATHPART
         if [ $? -eq 0 ]; then return 0; fi
      done
   else
      # try to find PATHPART only on the given device
      PATHPART="`echo \"$2\" | egrep_o \"^/dev/[^/]+/(.*)\"`"
      find_filepath $1 $DEVPART $PATHPART
   fi
}

# ===========================================================
# hardware preparation functions
# ===========================================================

# Create block devices to /dev described by /sys entries
#
mdev_start_hotplug()
{
   echolog "creating /dev entries for block devices"
   mdev -s
   echo /bin/mdev > /proc/sys/kernel/hotplug
}

# modprobe kernel modules needed for the LiveCD
#
modprobe_essential_modules()
{
   PRINTK=`cat /proc/sys/kernel/printk`
   echo "0" >/proc/sys/kernel/printk

   echolog "starting loop device support"
   modprobe_module loop max_loop=255
   echolog "starting cdrom filesystem support"
   modprobe_module isofs
   echolog "starting squashfs support"
   modprobe_module squashfs
   echolog "starting aufs support"
   modprobe_module aufs
   echolog "starting vfat support"
   modprobe_module nls_cp437
   modprobe_module nls_iso8859-1
   modprobe_module nls_iso8859-2
   modprobe_module vfat
   echolog "starting ntfs support"
   modprobe_module ntfs

   echo "$PRINTK" >/proc/sys/kernel/printk
}

# modprobe kernel modules needed for USB masstorage devices
#
modprobe_usb_modules()
{
   PRINTK=`cat /proc/sys/kernel/printk`
   echo "0" >/proc/sys/kernel/printk

   LSPCI="`lspci -v | grep -i prog-if`"
   if [ "`echo $LSPCI | egrep -i [eou]hci`" = "" ]; then
      return
   fi

   echolog "starting USB support..."
   if [ "`echo $LSPCI | grep -i ehci`" != "" ]; then
      modprobe_module ehci-hcd
   fi
   if [ "`echo $LSPCI | grep -i ohci`" != "" ]; then
      modprobe_module ohci-hcd
   fi
   if [ "`echo $LSPCI | grep -i uhci`" != "" ]; then
      modprobe_module uhci-hcd
   fi
   modprobe_module usb-storage

   SLEEP="`cmdline_value waitusb | sed -r 's/[^0-9]*([0-9]+).*/\1/'`"
   if [ "$SLEEP" = "" ]; then SLEEP=10; fi

   sleep $SLEEP
   echo "$PRINTK" >/proc/sys/kernel/printk
}

# enable/disable CD autoejecting when unmounted
# $1 = 1|0 ... enable|disable
#
cd_autoeject()
{
   echo $1 >/proc/sys/dev/cdrom/autoeject
}

# Disable DMA if nodma boot parameter is present
#
setup_dma()
{
   if [ ! "`cmdline_parameter nodma`" = "" ]; then
      for DEVICE in `list_cdrom_devices` `list_disk_devices`; do
         echolog "setting DMA support off for $DEVICE"
         hdparm -d 0 $DEVICE
      done
   fi
}

# update given line in fstab, add new values only if the device is not found
# $1 = fstab file to parse
# $2 = device name
# $3 = mountpoint
# $4 = filesystem
# $5 = mount options
#
fstab_update_line()
{
   if [ "`cat \"$1\" | sed -r \"s/#.*//\" | egrep \"^[[:space:]]*[^[:space:]]+[[:space:]]+$2[[:space:]]+\"`" = "" ]; then
      echo "$2" "$3" "$4" "$5" 0 0 "$FSTABLLFLAG" >>$1
   fi
}

# create correct fstab file in $1/etc/fstab and create apropriate
# mount directories in $1/mnt. Check for iocharset boot option,
# if present, add iocharset to all DOS/Win filesystems (vfat,ntfs)
# $1 = root directory (union)
#
fstab_update()
{
   IOCHARSET="`cmdline_value iocharset`"
   AUTO="`cmdline_parameter noauto`"
   if [ "$AUTO" = "" ]; then AUTO="auto"; fi

   FSTAB="$1/etc/fstab"
   mkdir -p $1/etc $1/mnt
   cat $FSTAB 2>/dev/null | grep -v "$FSTABLLFLAG" >$FSTAB~

   fstab_update_line $FSTAB~ tmpfs / tmpfs defaults
   fstab_update_line $FSTAB~ devpts /dev/pts devpts gid=5,mode=620
   fstab_update_line $FSTAB~ proc /proc proc defaults
   list_cdrom_devices | while read DEVICE; do
      MOUNTDIR="/mnt/`basename $DEVICE`_cdrom"
      mkdir -p $1/$MOUNTDIR
      fstab_update_line $FSTAB~ $DEVICE $MOUNTDIR iso9660 noauto,users,exec
   done
   list_partition_devices | while read DEVICE; do
      unset REMOVABLE; unset OPT; DEV="`basename $DEVICE`"; DEV0="`echo $DEV | cut -b 1-3`"
      if [ "0`cat /sys/block/$DEV0/removable 2>/dev/null`" -ne 0 ]; then
         REMOVABLE="_removable"
      fi

      MOUNTDIR="/mnt/$DEV$REMOVABLE"
      FS="`blkid -s TYPE $DEVICE | cut -d = -f 2 | tr -d ' \"'`"

      # add special options for NTFS
      if [ "$FS" = "ntfs" ]; then
         OPT=",ro"
#	 FS="ntfs-3g"
         if [ "$IOCHARSET" != "" ]; then OPT="$OPT,nls=$IOCHARSET"; fi
      fi

      # add special options for VFAT
      if [ "$FS" = "vfat" -a "$IOCHARSET" != ""  ]; then OPT=",iocharset=$IOCHARSET"; fi

      # if the partition has filesystem, add it to fstab
      if [ "$FS" != "" ]; then
         if [ "$FS" = "swap" ]; then
            fstab_update_line $FSTAB~ $DEVICE swap swap $AUTO,defaults
         else
            fstab_update_line $FSTAB~ $DEVICE $MOUNTDIR $FS $AUTO,noatime,users,suid,dev,exec$OPT
            mkdir -p "$1/$MOUNTDIR"
         fi
      fi
   done

   fstab_update_line $FSTAB~ /dev/fd0 /mnt/floppy vfat,msdos noauto,noatime,users,suid,dev,exec
   mkdir -p $1/mnt/floppy
   
   mv -f $FSTAB~ $FSTAB
}
