#!/bin/bash
# Use module while running LiveCD - include it into directory structure on the fly
# Author: Tomas Matejicek <http://www.linux-live.org>
#


if [ "$1" = "" ]; then
   echo
   echo "Use module on the fly while running Live CD"
   echo "Usage: $0 module.img"
   exit
fi

if [ -a ./liblinuxlive ]; then
   . ./liblinuxlive
else
   . /usr/lib/liblinuxlive || exit 1
fi

# for preinsert and postinsert scripts
# $MANUAL is set only by moduse.
# else (during LiveCD boot) it's unset.
#
MANUAL=true

IMGRO=/mnt/livecd/imgro/
IMGRW=/mnt/livecd/imgrw/

if [ ! -a "$IMGRO" -o ! -a "$IMGRW" ]; then
   "Error: You can use modules only while running a Live CD"
   exit 1
fi

MODULE="`basename $1`"
INSORDER=/tmp/moduse$$

rm -f "$INSORDER"
mount_img "$1" "$IMGRO" "$INSORDER"

IMG="`cat $INSORDER`"
IMG=$IMGRW/${IMG:${#IMGRO}}

if [ -x "$IMG/preinsert" ]; then "$IMG/preinsert"; fi
make_links "$IMG/data" "/" ""
if [ -x "$IMG/postinsert" ]; then "$IMG/postinsert"; fi

rm -f "$INSORDER"
